.TH HASKOBAN 1 "December 2014"

.SH NAME
haskoban

.SH SYNOPSIS
.B haskoban
[-l level-file]

.SH DESCRIPTION
All the box pushing goodness from sokoban in your terminal!

Explore the wonders of being a warehouse worker working
overtime without extra pay!

.SH OPTIONS
.I "\-l"
Load a specific level

.SH CONTROLS
.SS Movement
use wasd to move around the warehouse and do your pushing duties
.SS Exit
use q to quit your job

.SH AUTHOR
Noah Morrison <noah@morrison.ph>

.SH LICENSE
MIT
